---
title: " | The Sitting Hun"
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
    title:
    description:
    social-image: "/uploads/siteimage.jpg"
- scope:
    path: ''
    type: projects
  values:
    layout: project
    title:
    description:
    cover-image:
    primary-asset:
    primary-embed:
    awards:
    - name:
      path:
    info:
    - type: Image
      asset:
      text:
      style: Left, Right, Float
pagination:
  enabled: true
  debug: true
description: The brand and portfolio of Atthar Mirza & Company.
email: thesittinghun@gmail.com
baseurl:
url: https://www.thesittinghun.com
github_username: attharmirza
sass:
  sass_dir: _styles
  style: compressed
plugins:
  - jekyll-paginate-v2
