backend:
  name: git-gateway
  branch: production

media_folder: "_uploads"
public_folder: "uploads"

collections:
  - name: ""
  - label: "General"
  - folder: ""
  - create: true
  - fields:
    - {label: "Layout", name: "layout", widget: "string", default: "default"}
