backend:
  name: git-gateway
  branch: production

media_folder: "_uploads"
public_folder: "uploads"

logo_url: https://www.thesittinghun.com/graphics/logo.svg

collections:
  - editor:
      preview: false
    name: "configs"
    label: "General"
    create: false
    files:
      - label: "Site Parameters"
        name: "_config"
        file: "_config.yml"
        fields:
          - {label: Site Title, name: title, widget: string, default:}
          - {label: Site Description, name: description, widget: text, default:}

  - editor:
      preview: false
    name: "pages"
    label: "Pages"
    folder: "/"
    create: true
    fields:
      - {label: Title, name: title, widget: string, default: Other}
      - {label: Layout, name: layout, widget: string, default: default}
      - {label: Date, name: date, widget: date, default:}
      - {label: Description, name: description, widget: text, default: The professional portfolio of animator and web developer Atthar Mirza.}
      - {label: Content, name: body, widget: markdown, default: What's up my dude, this here is some default text., required: false}
      - label: "Pagination"
        name: "pagination"
        widget: "object"
        fields:
          - {label: Enabled, name: enabled, widget: boolean, default: false}
          - {label: collection, name: collection, widget: hidden, default:}
          - {label: permalink, name: permalink, widget: hidden, default:}
          - {label: Objects, name: per_page, widget: number, default: 10, valueType: int}
          - {label: sort_field, name: sort_field, widget: hidden, default:}
          - {label: sort_reverse, name: sort_reverse, widget: hidden, default:}
          - {label: indexpage, name: indexpage, widget: hidden, default:}

  - editor:
      preview: false
    name: "projects"
    label: "Projects"
    folder: "_projects"
    create: true
    slug: "{{slug}}"
    extension: "markdown"
    fields:
      - {label: Layout, name: layout, widget: hidden, default: project}
      - {label: Title, name: title, widget: string, default: }
      - {label: Position, name: position, widget: number, default: , valueType: int}
      - {label: Date, name: date, widget: date, default: }
      - {label: Description, name: description, widget: text, default: }
      - {label: Cover, name: cover-image, widget: image, default: }
      - label: "Awards"
        name: "awards"
        widget: "list"
        fields:
          - {label: Name, name: name, widget: string, default: , required: false}
          - {label: Image, name: path, widget: image, default: , required: false}
      - {label: Content, name: body, widget: markdown, default: Add the overall description of the project here.}
      - label: "Info"
        name: "info"
        widget: "list"
        fields:
          - {label: Type, name: type, widget: string, default: }
          - {label: Asset, name: asset, widget: file, default: , required: false}
          - {label: Text, name: text, widget: text, default: , required: false}
          - {label: Style, name: style, widget: hidden, default: Float}
